-- AlterTable
ALTER TABLE "livro" ADD COLUMN "codLivro" TEXT;
ALTER TABLE "livro" ADD COLUMN "dataEmprestimo" DATETIME;
ALTER TABLE "livro" ADD COLUMN "dataEntrega" DATETIME;
ALTER TABLE "livro" ADD COLUMN "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "livro" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
